image_width: 320
image_height: 240
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [293.75784,   0.     , 155.04753,
           0.     , 293.4901 , 120.42199,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.103375, -0.185659, 0.002115, 0.000400, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [297.17865,   0.     , 154.62837,   0.     ,
           0.     , 296.50058, 120.28298,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
